name: not_volga
description: "NOT-volga - Open source client and ticket generator for Tver transport."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  html: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icon/
    - assets/images/
    - assets/icons/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
