name: not_volga
description: "NOT-volga - Open source client and ticket generator for Tver transport."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  html: ^0.15.7
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  mobile_scanner: ^7.4.0
  yandex_mapkit: 4.2.1
  geolocator: ^14.0.3
  intl: ^0.20.3
  qr_flutter: ^4.1.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icon/
    - assets/images/
    - assets/icons/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
